export const GET_DEMANDES_CLIENT = "GET_DEMANDES_CLIENT";
export const GET_DEMANDES_CHEF = "GET_DEMANDES_CHEF";
// export const POST_DEMANDES = "POST_DEMANDES";
// export const EDIT_DEMANDES = "EDIT_DEMANDES";
// export const DELETE_DEMANDES = "DELETE_DEMANDES";

export const FAIL_DEMANDES = "FAIL_DEMANDES";
export const LOAD_DEMANDES = "LOAD_DEMANDES";
