export const GET_DEMANDES_CLIENT = "GET_DEMANDES_CLIENT";
export const GET_DEMANDES_CHEF = "GET_DEMANDES_CHEF";

export const FAIL_DEMANDES = "FAIL_DEMANDES";
export const LOAD_DEMANDES = "LOAD_DEMANDES";
